#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#define PAGE_SIZE 4096

static uintptr_t region_base = 0;
static size_t region_size = 0;

static void process_address(uintptr_t address)
{
    if (region_base == 0)
        return;

    if (address < region_base)
        return;

    uintptr_t end =
        region_base + region_size;

    if (address >= end)
        return;

    /*
     * Convert the ACTUAL runtime virtual address
     * into the page number inside the actual allocation.
     */
    unsigned long page =
        (unsigned long)((address - region_base) /
                        PAGE_SIZE);

    /*
     * AIPage input format.
     *
     * The page ID is derived from the real address.
     */
    printf("%lu\n", page);
    fflush(stdout);
}

int main(void)
{
    char line[1024];

    while (fgets(line, sizeof(line), stdin))
    {
        /*
         * Runtime allocation marker generated by
         * real_memory_workload.
         */
        if (strncmp(line, "AIPAGE_REGION ", 14) == 0)
        {
            char address_text[64];
            unsigned long size;

            if (sscanf(line,
                       "AIPAGE_REGION %63s %lu",
                       address_text,
                       &size) == 2)
            {
                region_base =
                    (uintptr_t)strtoull(
                        address_text,
                        NULL,
                        16);

                region_size = size;

                fprintf(stderr,
                        "AIPage REAL MEMORY REGION: base=%p size=%zu bytes pages=%zu\n",
                        (void *)region_base,
                        region_size,
                        region_size / PAGE_SIZE);
            }

            continue;
        }

        /*
         * Valgrind Lackey memory-access format:
         *
         * L address,size
         * S address,size
         * M address,size
         *
         * We care about actual LOAD/STORE addresses.
         */
        char type;
        char address_text[64];
        unsigned long size;

        if (sscanf(line,
                   " %c %63[^,],%lu",
                   &type,
                   address_text,
                   &size) == 3)
        {
            if (type == 'L' ||
                type == 'S' ||
                type == 'M')
            {
                uintptr_t address =
                    (uintptr_t)strtoull(
                        address_text,
                        NULL,
                        16);

                process_address(address);
            }
        }
    }

    return 0;
}
